### ISSUE TITLE
Make Mapper more robust for API Changes

### ISSUE THREAD

**Issue by bastianschwarz** [livereach/public-api-php#1]
If the API changes (fields are added to items), the mapper throws an Exception since the property does not exist in the feedItem.

This breaks the implementation if the consumer is not updated immediately.

So before updating from 2.0.1 to 2.0.2 the following exception was thrown in production:

`exception 'JsonMapper_Exception' with message 'JSON property "friendCount" does not exist in object of type LivereachPublicApi\dto\FeedItem' in /home/wwwdev/workspace/htdocs/tirol/vendor/netresearch/jsonmapper/src/JsonMapper.php:158`

IMHO a first step could be to just log fields the API returns but that are not present in the entity and just skip them for now.

**Comment by misternerd** [comment]
@bastianschwarz In version 2.0.3, the JSON mapper has now been configured to not throw an exception (check commit `88572ce81a11268c3f91de0e502f1205cbab1199`) on encountering unknown properties.
