### ISSUE TITLE
Date broken

### ISSUE THREAD

**Issue by Suranex** [livereach/public-api-php#2]
The date of (at least) facebook feed items seems to be broken recently. 

example feed item (reduced):
```
	{
		"id": 34015489,
		"uid": "FP1199970343422781_1676723552414122",
		"type": "FACEBOOK_PAGE",
		"date": "2018-03-12T15:30:00.000+0000",
		[...]
	},
```

The date is 2018-03-12T15:30:00.000+0000, but in https://github.com/livereach/public-api-php/blob/master/src/LivereachPublicApi/dto/Date.php the script do a division by 1000, which can not be successfully done because it is not a timestamp/int. 

Therefore the date is now always 1970-01-01 01:00:02.000000.

**Comment by misternerd** [comment]
@Suranex Thank you for reporting the issue. We have now fixed it on our servers, so you don't need to update any client libraries. Sorry for the inconvenience.
